/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.proto.Message');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.proto.Attack');
goog.require('proto.proto.Move');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.proto.Message.oneofGroups_);
};
goog.inherits(proto.proto.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.Message.displayName = 'proto.proto.Message';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.proto.Message.oneofGroups_ = [[11,12]];

/**
 * @enum {number}
 */
proto.proto.Message.ContentCase = {
  CONTENT_NOT_SET: 0,
  MOVE: 11,
  ATTACK: 12
};

/**
 * @return {proto.proto.Message.ContentCase}
 */
proto.proto.Message.prototype.getContentCase = function() {
  return /** @type {proto.proto.Message.ContentCase} */(jspb.Message.computeOneofCase(this, proto.proto.Message.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, ""),
    move: (f = msg.getMove()) && proto.proto.Move.toObject(includeInstance, f),
    attack: (f = msg.getAttack()) && proto.proto.Attack.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.Message}
 */
proto.proto.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.Message;
  return proto.proto.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.Message}
 */
proto.proto.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 11:
      var value = new proto.proto.Move;
      reader.readMessage(value,proto.proto.Move.deserializeBinaryFromReader);
      msg.setMove(value);
      break;
    case 12:
      var value = new proto.proto.Attack;
      reader.readMessage(value,proto.proto.Attack.deserializeBinaryFromReader);
      msg.setAttack(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMove();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.proto.Move.serializeBinaryToWriter
    );
  }
  f = message.getAttack();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.proto.Attack.serializeBinaryToWriter
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.proto.Message.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.proto.Message.prototype.setPath = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Move move = 11;
 * @return {?proto.proto.Move}
 */
proto.proto.Message.prototype.getMove = function() {
  return /** @type{?proto.proto.Move} */ (
    jspb.Message.getWrapperField(this, proto.proto.Move, 11));
};


/** @param {?proto.proto.Move|undefined} value */
proto.proto.Message.prototype.setMove = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.proto.Message.oneofGroups_[0], value);
};


proto.proto.Message.prototype.clearMove = function() {
  this.setMove(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.Message.prototype.hasMove = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Attack attack = 12;
 * @return {?proto.proto.Attack}
 */
proto.proto.Message.prototype.getAttack = function() {
  return /** @type{?proto.proto.Attack} */ (
    jspb.Message.getWrapperField(this, proto.proto.Attack, 12));
};


/** @param {?proto.proto.Attack|undefined} value */
proto.proto.Message.prototype.setAttack = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.proto.Message.oneofGroups_[0], value);
};


proto.proto.Message.prototype.clearAttack = function() {
  this.setAttack(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.Message.prototype.hasAttack = function() {
  return jspb.Message.getField(this, 12) != null;
};


